// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// AuthMock is an autogenerated mock type for the Auth type
type AuthMock struct {
	mock.Mock
}

type AuthMock_Expecter struct {
	mock *mock.Mock
}

func (_m *AuthMock) EXPECT() *AuthMock_Expecter {
	return &AuthMock_Expecter{mock: &_m.Mock}
}

// SignIn provides a mock function with given fields: ctx, username, password
func (_m *AuthMock) SignIn(ctx context.Context, username string, password string) (string, error) {
	ret := _m.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for SignIn")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, username, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, username, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthMock_SignIn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignIn'
type AuthMock_SignIn_Call struct {
	*mock.Call
}

// SignIn is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *AuthMock_Expecter) SignIn(ctx interface{}, username interface{}, password interface{}) *AuthMock_SignIn_Call {
	return &AuthMock_SignIn_Call{Call: _e.mock.On("SignIn", ctx, username, password)}
}

func (_c *AuthMock_SignIn_Call) Run(run func(ctx context.Context, username string, password string)) *AuthMock_SignIn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *AuthMock_SignIn_Call) Return(_a0 string, _a1 error) *AuthMock_SignIn_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthMock_SignIn_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *AuthMock_SignIn_Call {
	_c.Call.Return(run)
	return _c
}

// SignUp provides a mock function with given fields: ctx, username, password
func (_m *AuthMock) SignUp(ctx context.Context, username string, password string) (string, error) {
	ret := _m.Called(ctx, username, password)

	if len(ret) == 0 {
		panic("no return value specified for SignUp")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return rf(ctx, username, password)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = rf(ctx, username, password)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// AuthMock_SignUp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SignUp'
type AuthMock_SignUp_Call struct {
	*mock.Call
}

// SignUp is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - password string
func (_e *AuthMock_Expecter) SignUp(ctx interface{}, username interface{}, password interface{}) *AuthMock_SignUp_Call {
	return &AuthMock_SignUp_Call{Call: _e.mock.On("SignUp", ctx, username, password)}
}

func (_c *AuthMock_SignUp_Call) Run(run func(ctx context.Context, username string, password string)) *AuthMock_SignUp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *AuthMock_SignUp_Call) Return(_a0 string, _a1 error) *AuthMock_SignUp_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *AuthMock_SignUp_Call) RunAndReturn(run func(context.Context, string, string) (string, error)) *AuthMock_SignUp_Call {
	_c.Call.Return(run)
	return _c
}

// NewAuthMock creates a new instance of AuthMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthMock {
	mock := &AuthMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
