// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/angryscorp/gophermart/internal/domain/model"
	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// OrdersMock is an autogenerated mock type for the Orders type
type OrdersMock struct {
	mock.Mock
}

type OrdersMock_Expecter struct {
	mock *mock.Mock
}

func (_m *OrdersMock) EXPECT() *OrdersMock_Expecter {
	return &OrdersMock_Expecter{mock: &_m.Mock}
}

// AllOrders provides a mock function with given fields: ctx, userID
func (_m *OrdersMock) AllOrders(ctx context.Context, userID uuid.UUID) ([]model.Order, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for AllOrders")
	}

	var r0 []model.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]model.Order, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []model.Order); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OrdersMock_AllOrders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AllOrders'
type OrdersMock_AllOrders_Call struct {
	*mock.Call
}

// AllOrders is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *OrdersMock_Expecter) AllOrders(ctx interface{}, userID interface{}) *OrdersMock_AllOrders_Call {
	return &OrdersMock_AllOrders_Call{Call: _e.mock.On("AllOrders", ctx, userID)}
}

func (_c *OrdersMock_AllOrders_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *OrdersMock_AllOrders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *OrdersMock_AllOrders_Call) Return(_a0 []model.Order, _a1 error) *OrdersMock_AllOrders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OrdersMock_AllOrders_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]model.Order, error)) *OrdersMock_AllOrders_Call {
	_c.Call.Return(run)
	return _c
}

// UploadOrder provides a mock function with given fields: ctx, orderNumber, userID
func (_m *OrdersMock) UploadOrder(ctx context.Context, orderNumber string, userID uuid.UUID) error {
	ret := _m.Called(ctx, orderNumber, userID)

	if len(ret) == 0 {
		panic("no return value specified for UploadOrder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, uuid.UUID) error); ok {
		r0 = rf(ctx, orderNumber, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OrdersMock_UploadOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadOrder'
type OrdersMock_UploadOrder_Call struct {
	*mock.Call
}

// UploadOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - orderNumber string
//   - userID uuid.UUID
func (_e *OrdersMock_Expecter) UploadOrder(ctx interface{}, orderNumber interface{}, userID interface{}) *OrdersMock_UploadOrder_Call {
	return &OrdersMock_UploadOrder_Call{Call: _e.mock.On("UploadOrder", ctx, orderNumber, userID)}
}

func (_c *OrdersMock_UploadOrder_Call) Run(run func(ctx context.Context, orderNumber string, userID uuid.UUID)) *OrdersMock_UploadOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *OrdersMock_UploadOrder_Call) Return(_a0 error) *OrdersMock_UploadOrder_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *OrdersMock_UploadOrder_Call) RunAndReturn(run func(context.Context, string, uuid.UUID) error) *OrdersMock_UploadOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewOrdersMock creates a new instance of OrdersMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrdersMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrdersMock {
	mock := &OrdersMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
