// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	Number     string
	Status     string
	Accrual    pgtype.Numeric
	UploadedAt pgtype.Timestamp
	UserID     uuid.UUID
}
