// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	Number     string
	Username   string
	Status     string
	Accrual    int32
	UploadedAt pgtype.Timestamp
}
