// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const checkUsername = `-- name: CheckUsername :one
SELECT EXISTS(
    SELECT 1 FROM users
    WHERE username = $1
) AS user_exists
`

func (q *Queries) CheckUsername(ctx context.Context, username string) (bool, error) {
	row := q.db.QueryRow(ctx, checkUsername, username)
	var user_exists bool
	err := row.Scan(&user_exists)
	return user_exists, err
}

const createBalance = `-- name: CreateBalance :exec
INSERT INTO balances (user_id, balance, withdrawn)
VALUES ($1, 0, 0)
`

func (q *Queries) CreateBalance(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, createBalance, userID)
	return err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, username, password_hash)
VALUES ($1, $2, $3)
`

type CreateUserParams struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser, arg.ID, arg.Username, arg.PasswordHash)
	return err
}

const userByUsername = `-- name: UserByUsername :one
SELECT id, username, password_hash FROM users
WHERE username = $1
`

type UserByUsernameRow struct {
	ID           uuid.UUID
	Username     string
	PasswordHash string
}

func (q *Queries) UserByUsername(ctx context.Context, username string) (UserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, userByUsername, username)
	var i UserByUsernameRow
	err := row.Scan(&i.ID, &i.Username, &i.PasswordHash)
	return i, err
}
