// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: query.sql

package db

import (
	"context"
)

const checkUser = `-- name: CheckUser :one
SELECT 1 FROM users
WHERE username = $1 AND password_hash = $2
`

type CheckUserParams struct {
	Username     string
	PasswordHash string
}

func (q *Queries) CheckUser(ctx context.Context, arg CheckUserParams) (int32, error) {
	row := q.db.QueryRow(ctx, checkUser, arg.Username, arg.PasswordHash)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (username, password_hash)
VALUES ($1, $2)
`

type CreateUserParams struct {
	Username     string
	PasswordHash string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser, arg.Username, arg.PasswordHash)
	return err
}
